data = ""
data += "#pico-tpm.py - 29/08/2021 @ 01:17\n"
data += "import hashlib\n"
data += "\n"
data += "def main():\n"
data += "    Header = \"[TPM]: \"\n"
data += "    HashFile = \"hashfile.txt\"\n"
data += "    Hashes = []\n"
data += "    \n"
data += "    CommandStore = \"store\"\n"
data += "    CommandFetch = \"fetch\"\n"
data += "    \n"
data += "    ResponseOK = \"OK\"\n"
data += "    ResponseError = \"ERROR\"\n"
data += "    \n"
data += "    while True:\n"
data += "        try:\n"
data += "            userInput = input(Header)\n"
data += "            command = userInput.split(\" \", 1)\n"
data += "            \n"
data += "            file = open(HashFile, \"r\")\n"
data += "            data = file.read()\n"
data += "            file.close()\n"
data += "            \n"
data += "            Hashes = data.splitlines()\n"
data += "            hash = str(hashlib.sha256(command[1]).digest())\n"
data += "            \n"
data += "            if (command[0].lower() == CommandStore):\n"
data += "                Hashes.append(hash)\n"
data += "                \n"
data += "                data = \"\\n\".join(x for x in Hashes)\n"
data += "                file = open(HashFile, \"w\")\n"
data += "                file.write(data)\n"
data += "                file.close()\n"
data += "                \n"
data += "                Hashes = []\n"
data += "                print(Header + ResponseOK)\n"
data += "                \n"
data += "            elif (command[0].lower() == CommandFetch):\n"
data += "                match = False\n"
data += "                \n"
data += "                for line in Hashes:\n"
data += "                    if (line == hash):\n"
data += "                        print(Header + hash)\n"
data += "                        match = True\n"
data += "                        break\n"
data += "                \n"
data += "                if (match == False):\n"
data += "                    raise\n"
data += "                \n"
data += "            else:\n"
data += "                raise\n"
data += "        except:\n"
data += "            print(Header + ResponseError)\n"
data += "\n"
data += "if __name__ == \"__main__\":\n"
data += "    main()\n"
file = open("pico_tpm.py", "w")
file.write(data)
file.close()